"""Structured Pydantic response schemas for LLM outputs."""

from typing import List, Optional
from pydantic import BaseModel, Field

from app.models.state import AgentPlan, PlanStep


class PlanGenerationOutput(BaseModel):
    """Output generated by Planner Agent."""
    objective: str = Field(..., description="High-level goal statement")
    architecture_overview: str = Field(..., description="Architectural approach and rationale")
    steps: List[PlanStep] = Field(..., description="Ordered list of discrete steps")


class DebugAnalysisOutput(BaseModel):
    """Output generated by Debugger Agent."""
    root_cause: str = Field(..., description="Explanation of why the tests or commands failed")
    proposed_fix: str = Field(..., description="Specific fix instructions for the coding stage")
    files_to_modify: List[str] = Field(default_factory=list, description="Target files needing adjustments")


class ReviewSummaryOutput(BaseModel):
    """Output generated by Reviewer Agent."""
    summary: str = Field(..., description="Summary of changes and enhancements")
    commit_message: str = Field(
        ..., description="Conventional commits formatted git commit message"
    )
    is_ready_for_commit: bool = Field(
        default=True, description="Whether the changes are clean and complete"
    )
