"""LangGraph State Models and Execution Payloads."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from app.models.enums import ApprovalStatus, WorkflowPhase


def utc_now() -> datetime:
    """Return timezone-aware current UTC datetime."""
    return datetime.now(timezone.utc)


class ToolExecutionRecord(BaseModel):
    """Traceable log of a single tool execution."""
    call_id: str
    tool_name: str
    input_args: Dict[str, Any] = Field(default_factory=dict)
    output: Optional[str] = None
    error: Optional[str] = None
    exit_code: Optional[int] = None
    execution_time_ms: float = 0.0
    requires_approval: bool = False
    approval_status: ApprovalStatus = ApprovalStatus.NOT_REQUIRED
    timestamp: datetime = Field(default_factory=utc_now)


class PlanStep(BaseModel):
    """An individual step inside the agent's implementation plan."""
    step_id: int
    title: str
    description: str
    target_files: List[str] = Field(default_factory=list)
    completed: bool = False
    notes: Optional[str] = None


class AgentPlan(BaseModel):
    """Structured implementation plan generated by the planning agent."""
    objective: str
    architecture_overview: str
    steps: List[PlanStep] = Field(default_factory=list)
    current_step_index: int = 0


class TestExecutionSummary(BaseModel):
    """Result of running tests in the sandbox."""
    __test__ = False  # Inform pytest this is a data schema, not a test suite

    command: str
    passed: bool
    total_tests: int = 0
    failures: int = 0
    errors: int = 0
    stdout: str = ""
    stderr: str = ""
    exit_code: int = 0
    duration_seconds: float = 0.0


class PendingApproval(BaseModel):
    """Details of an action currently paused for human approval."""
    action_type: str
    tool_name: str
    payload: Dict[str, Any]
    reason: str
    requested_at: datetime = Field(default_factory=utc_now)


class AgentState(BaseModel):
    """LangGraph typed state container across the autonomous engineering lifecycle."""
    task_id: str
    repository_url: str
    base_branch: str = "main"
    working_branch: str
    workspace_path: str
    user_instruction: str

    # Workflow Phase Tracking
    current_phase: WorkflowPhase = WorkflowPhase.INITIALIZED

    # Repository Analysis & Knowledge
    repo_structure: Dict[str, Any] = Field(default_factory=dict)
    file_list: List[str] = Field(default_factory=list)
    key_files: List[str] = Field(default_factory=list)
    detected_framework: Optional[str] = None
    detected_test_command: Optional[str] = None

    # Implementation Planning
    plan: Optional[AgentPlan] = None

    # Code Modifications & Tool Audit
    tool_history: List[ToolExecutionRecord] = Field(default_factory=list)
    modified_files: List[str] = Field(default_factory=list)

    # Testing & Debugging Loop
    test_results: List[TestExecutionSummary] = Field(default_factory=list)
    retry_count: int = 0
    max_retries: int = 5

    # Human-In-The-Loop Checkpoint
    pending_approval: Optional[PendingApproval] = None
    last_human_feedback: Optional[str] = None

    # Final Outcome & Deliverables
    review_summary: Optional[str] = None
    commit_sha: Optional[str] = None
    pull_request_url: Optional[str] = None
    error_message: Optional[str] = None
