"""LangGraph State Models and Execution Payloads."""

import json
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, model_validator

from app.models.enums import ApprovalStatus, WorkflowPhase


def utc_now() -> datetime:
    """Return timezone-aware current UTC datetime."""
    return datetime.now(timezone.utc)


class ToolExecutionRecord(BaseModel):
    """Traceable log of a single tool execution."""
    call_id: str
    tool_name: str
    input_args: Dict[str, Any] = Field(default_factory=dict)
    output: Optional[str] = None
    error: Optional[str] = None
    exit_code: Optional[int] = None
    execution_time_ms: float = 0.0
    requires_approval: bool = False
    approval_status: ApprovalStatus = ApprovalStatus.NOT_REQUIRED
    timestamp: datetime = Field(default_factory=utc_now)


class PlanStep(BaseModel):
    """Individual action step in an execution plan."""
    step_id: int
    title: str
    description: str
    target_files: List[str] = Field(default_factory=list)
    status: str = "pending"  # pending, in_progress, completed, failed
    completed: bool = False
    notes: Optional[str] = None


class AgentPlan(BaseModel):
    """Structured implementation plan generated by the planning agent."""
    objective: str
    architecture_overview: str
    steps: List[PlanStep] = Field(default_factory=list)
    current_step_index: int = 0


class TestExecutionSummary(BaseModel):
    """Result of running tests in the sandbox."""
    __test__ = False  # Inform pytest this is a data schema, not a test suite

    command: str = ""
    passed: bool = False
    total_tests: int = 0
    failures: int = 0
    errors: int = 0
    stdout: str = ""
    stderr: str = ""
    exit_code: int = 0
    duration_seconds: float = 0.0

    @model_validator(mode="before")
    @classmethod
    def _normalize_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            d = dict(data)
            # If 'passed' not provided but 'is_success' is
            if "passed" not in d and "is_success" in d:
                d["passed"] = bool(d["is_success"])
            # If nested 'result' dict is provided
            if isinstance(d.get("result"), dict):
                res = d["result"]
                if not d.get("command") and "command" in res:
                    d["command"] = res["command"]
                if "passed" not in d:
                    d["passed"] = res.get("passed", res.get("is_success", False))
                if not d.get("stdout") and res.get("stdout"):
                    d["stdout"] = res.get("stdout")
                elif not d.get("stdout") and res.get("output"):
                    d["stdout"] = res.get("output")
                if not d.get("stderr") and res.get("stderr"):
                    d["stderr"] = res.get("stderr")
                if not d.get("exit_code") and "exit_code" in res:
                    d["exit_code"] = res.get("exit_code")
                if not d.get("total_tests") and "total_tests" in res:
                    d["total_tests"] = int(res["total_tests"])
                elif not d.get("total_tests") and "total" in res:
                    d["total_tests"] = int(res["total"])
                if not d.get("failures") and "failures" in res:
                    d["failures"] = int(res["failures"])
                elif not d.get("failures") and "failed" in res:
                    d["failures"] = int(res["failed"])
                if not d.get("errors") and "errors" in res:
                    d["errors"] = int(res["errors"])
                if not d.get("duration_seconds") and "duration_seconds" in res:
                    d["duration_seconds"] = float(res["duration_seconds"])
            # If 'output' is provided instead of stdout
            if not d.get("stdout") and d.get("output"):
                d["stdout"] = d["output"]
            # If metadata contains metrics
            if isinstance(d.get("metadata"), dict):
                meta = d["metadata"]
                if "passed" not in d and "is_success" in meta:
                    d["passed"] = bool(meta["is_success"])
                if not d.get("total_tests") and "total" in meta:
                    d["total_tests"] = int(meta["total"])
                if not d.get("failures") and "failed" in meta:
                    d["failures"] = int(meta["failed"])
                if not d.get("errors") and "errors" in meta:
                    d["errors"] = int(meta["errors"])
            return d
        return data


class PendingApproval(BaseModel):
    """Details of an action currently paused for human approval."""
    approval_id: Optional[str] = None
    action_type: str = "tool_execution"
    tool_name: str
    action_payload: Dict[str, Any] = Field(default_factory=dict)
    payload: Dict[str, Any] = Field(default_factory=dict)
    reason: str = ""
    status: ApprovalStatus = ApprovalStatus.PENDING
    reviewer_feedback: Optional[str] = None
    created_at: datetime = Field(default_factory=utc_now)
    requested_at: Optional[datetime] = None

    @model_validator(mode="before")
    @classmethod
    def _normalize_approval(cls, data: Any) -> Any:
        if isinstance(data, dict):
            d = dict(data)
            # Sync approval_id / id
            if not d.get("approval_id") and d.get("id"):
                d["approval_id"] = d["id"]
            elif not d.get("id") and d.get("approval_id"):
                d["id"] = d["approval_id"]

            # Sync payload and action_payload
            if "action_payload" in d and "payload" not in d:
                d["payload"] = d["action_payload"]
            elif "payload" in d and "action_payload" not in d:
                d["action_payload"] = d["payload"]

            # Ensure payload/action_payload is a dict if JSON string
            if isinstance(d.get("action_payload"), str):
                try:
                    d["action_payload"] = json.loads(d["action_payload"])
                except Exception:
                    d["action_payload"] = {}
                d["payload"] = d["action_payload"]
            elif isinstance(d.get("payload"), str):
                try:
                    d["payload"] = json.loads(d["payload"])
                except Exception:
                    d["payload"] = {}
                d["action_payload"] = d["payload"]

            if d.get("action_payload") is None:
                d["action_payload"] = {}
            if d.get("payload") is None:
                d["payload"] = {}

            # Sync reason and reviewer_feedback
            if not d.get("reason"):
                if d.get("reviewer_feedback"):
                    d["reason"] = d["reviewer_feedback"]
                elif d.get("tool_name"):
                    d["reason"] = f"Action '{d['tool_name']}' requires human approval before execution."
                else:
                    d["reason"] = "Human approval required."

            # Sync created_at and requested_at
            if "requested_at" in d and "created_at" not in d:
                d["created_at"] = d["requested_at"]
            elif "created_at" in d and "requested_at" not in d:
                d["requested_at"] = d["created_at"]

            # Normalize status
            if "status" in d and isinstance(d["status"], str):
                try:
                    d["status"] = ApprovalStatus(d["status"])
                except ValueError:
                    d["status"] = ApprovalStatus.PENDING

            return d
        return data


class AgentState(BaseModel):
    """LangGraph typed state container across the autonomous engineering lifecycle."""
    task_id: str
    repository_url: str
    base_branch: str = "main"
    working_branch: str
    workspace_path: str
    user_instruction: str

    # Workflow Phase Tracking
    current_phase: WorkflowPhase = WorkflowPhase.INITIALIZED

    # Repository Analysis & Knowledge
    repo_structure: Dict[str, Any] = Field(default_factory=dict)
    file_list: List[str] = Field(default_factory=list)
    key_files: List[str] = Field(default_factory=list)
    detected_framework: Optional[str] = None
    detected_test_command: Optional[str] = None

    # Implementation Planning
    plan: Optional[AgentPlan] = None

    # Code Modifications & Tool Audit
    tool_history: List[ToolExecutionRecord] = Field(default_factory=list)
    modified_files: List[str] = Field(default_factory=list)

    # Testing & Debugging Loop
    test_results: List[TestExecutionSummary] = Field(default_factory=list)
    retry_count: int = 0
    max_retries: int = 5

    # Human-In-The-Loop Checkpoint
    pending_approval: Optional[PendingApproval] = None
    last_human_feedback: Optional[str] = None

    # Final Outcome & Deliverables
    review_summary: Optional[str] = None
    commit_sha: Optional[str] = None
    pull_request_url: Optional[str] = None
    error_message: Optional[str] = None
